schema_version: 1

context:
  version: "1.13"

package:
  name: msdfgen
  version: ${{ version }}

source:
  url: https://github.com/Chlumsky/msdfgen/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 93cd1ad8918c1a78c5c96e82d4f4c77f0eb86c2e7e8579a0967e54196c4b7167

build:
  number: 1

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
  host:
    - freetype
    - tinyxml2
    - libpng
    - zlib
    # - skia
  run_exports:
    weak:
      - ${{ pin_subpackage('msdfgen', upper_bound='x.x') }}

tests:
  - package_contents:
      include:
        - msdfgen/msdfgen.h
      lib:
        - msdfgen-core
        - msdfgen-ext
      bin:
        - msdfgen
  - script:
      - msdfgen --help

about:
  homepage: https://github.com/Chlumsky/msdfgen
  repository: https://github.com/Chlumsky/msdfgen
  summary: Multi-channel signed distance field generator
  description: |
    This is a utility for generating signed distance fields from vector shapes
    and font glyphs, which serve as a texture representation that can be used
    in real-time graphics to efficiently reproduce said shapes. Although it can
    also be used to generate conventional signed distance fields best known
    from this Valve paper and perpendicular distance fields, its primary
    purpose is to generate multi-channel distance fields, using a method I have
    developed. Unlike monochrome distance fields, they have the ability to
    reproduce sharp corners almost perfectly by utilizing all three color
    channels.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hmaarrfk
